services:
  - type: web
    name: fileshare
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn fileshare.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.3"
